=== DmitriNahorny/JavaTrainingTasks/Task8/web/resource/tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/tariffs" xmlns:tns="http://www.example.com/tariffs" elementFormDefault="qualified">
    <element name="tariff" type="tns:Tariff"></element>
    <element name="parameter" type="tns:Parameter"></element>
    <element name="call-prices" type="tns:Call-prices"></element>
    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Tariff">
        <sequence>
            <element name="operator-name" type="string" />
            <element name="payroll" type="nonNegativeInteger" />
            <element name="call-prices" type="tns:Call-prices" />
            <element name="sms-price" type="nonNegativeInteger" />
            <element name="parameter" type="tns:Parameter" />
        </sequence>
        <attribute name="name" type="string" />
    </complexType>
    <complexType name="Parameter">
        <sequence>
            <element name="favourite-number" type="nonNegativeInteger" />
            <element name="charging">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="second"></enumeration>
                        <enumeration value="12-seconds"></enumeration>
                        <enumeration value="minute"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="subscription-fee" type="nonNegativeInteger" />
        </sequence>
    </complexType>
    <complexType name="Call-prices">
        <sequence>
            <element name="within-network-call-price" type="nonNegativeInteger" />
            <element name="outside-network-call-price" type="nonNegativeInteger"/>
            <element name="stationary-call-price" type="nonNegativeInteger" />
        </sequence>
    </complexType>
</schema>

=== DmitriNahorny/JavaTrainingTasks/temp/Task7/resource/tariffs.xml
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.com/tariffs" xsi:schemaLocation="http://www.example.com/tariffs tariff.xsd">
    <tariff name="Comfort Standard">
        <operator-name>Velcom</operator-name>
        <payroll>990</payroll>
        <call-prices>
            <within-network-call-price>3</within-network-call-price>
            <outside-network-call-price>13</outside-network-call-price>
            <stationary-call-price>13</stationary-call-price>
        </call-prices>
        <sms-price>4</sms-price>
        <parameter>
            <favourite-number>0</favourite-number>
            <charging>12-seconds</charging>
            <subscription-fee>500</subscription-fee>
        </parameter>
    </tariff>
    <tariff name="Comfort Super">
        <operator-name>Velcom</operator-name>
        <payroll>1490</payroll>
        <call-prices>
            <within-network-call-price>2</within-network-call-price>
            <outside-network-call-price>10</outside-network-call-price>
            <stationary-call-price>10</stationary-call-price>
        </call-prices>
        <sms-price>4</sms-price>
        <parameter>
            <favourite-number>0</favourite-number>
            <charging>12-seconds</charging>
            <subscription-fee>500</subscription-fee>
        </parameter>
    </tariff>
    <tariff name="Comfort Premium">
        <operator-name>Velcom</operator-name>
        <payroll>1690</payroll>
        <call-prices>
            <within-network-call-price>1</within-network-call-price>
            <outside-network-call-price>8</outside-network-call-price>
            <stationary-call-price>8</stationary-call-price>
        </call-prices>
        <sms-price>4</sms-price>
        <parameter>
            <favourite-number>0</favourite-number>
            <charging>12-seconds</charging>
            <subscription-fee>500</subscription-fee>
        </parameter>
    </tariff>
    <tariff name="Comfort Platinum">
        <operator-name>Velcom</operator-name>
        <payroll>2190</payroll>
        <call-prices>
            <within-network-call-price>0</within-network-call-price>
            <outside-network-call-price>8</outside-network-call-price>
            <stationary-call-price>8</stationary-call-price>
        </call-prices>
        <sms-price>4</sms-price>
        <parameter>
            <favourite-number>0</favourite-number>
            <charging>12-seconds</charging>
            <subscription-fee>500</subscription-fee>
        </parameter>
    </tariff>
    <tariff name="Smart Unlimited">
        <operator-name>Velcom</operator-name>
        <payroll>4990</payroll>
        <call-prices>
            <within-network-call-price>0</within-network-call-price>
            <outside-network-call-price>8</outside-network-call-price>
            <stationary-call-price>8</stationary-call-price>
        </call-prices>
        <sms-price>0</sms-price>
        <parameter>
            <favourite-number>0</favourite-number>
            <charging>12-seconds</charging>
            <subscription-fee>4000</subscription-fee>
        </parameter>
    </tariff>
    <tariff name="Business Class">
        <operator-name>Velcom</operator-name>
        <payroll>9990</payroll>
        <call-prices>
            <within-network-call-price>0</within-network-call-price>
            <outside-network-call-price>7</outside-network-call-price>
            <stationary-call-price>7</stationary-call-price>
        </call-prices>
        <sms-price>0</sms-price>
        <parameter>
            <favourite-number>0</favourite-number>
            <charging>12-seconds</charging>
            <subscription-fee>9990</subscription-fee>
        </parameter>
    </tariff>
    <!--6 tariffs in total-->
</tariffs>
